### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by CorvetteCole** [Haidra-Org/horde-safety#1]
Unfortunately I cannot run https://github.com/db0/lemmy-safety right now because horde-safety is the only package that does not support Python 3.11. Is there a specific thing broken in 3.11?

**Comment by tazlin** [comment]
Can you either provide me with a specific error or suggest the reason you believe 3.11 is not supported? The package is limited, and I have just confirmed that the tests (which are not necessarily exhaustive) run OK with 3.11.

**Comment by CorvetteCole** [comment]
I'll get you an error message soon, but pip wouldn't install it due to requiring a lower python version (is what it said).

**Comment by tazlin** [comment]
Should be fixed as of https://github.com/Haidra-Org/horde-safety/commit/a940dfc7af700ad16b15d4fadb63ba157d94d4ea.

**Comment by tazlin** [comment]
The latest version on pypi has this change.

**Comment by CorvetteCole** [comment]
That is what I suspected the problem was! I'll give it a test in a little bit. Thanks!

**Comment by CorvetteCole** [comment]
Confirmed fixed now, thanks again.
